// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
//! The attach-APN configuration payload.
//!
//! `UtaMsCallPsAttachApnConfigReq` is by far the largest request the tool
//! sends. Its 203-specifier wire format and argument list are ported
//! byte-for-byte from the reverse-engineered `xmm7360-pci` implementation, so
//! it lives in its own module to keep the rest of the payload code readable.

use crate::codec::{self, Arg, CodecError};

/// Capacity of an APN string field, in bytes.
pub const APN_MAX_LEN: usize = 101;

/// Wire format string for the (very large) attach-APN configuration request.
const FORMAT: &str = "Bs260Ls66s65s250Bs252HLLLLLLLLLLLLLLLLLLLLLs20Ls104s260Ls66s65s250Bs252HLLLLLLLLLLLLLLLLLLLLLs20Ls104s260Ls66s65s250Bs252HLLLLLLLLLLLLLLLLLLLLLs20Ls104s260Ls66s65s250Bs252HLLLLLLLLLLLLLLLLLLLLLs20Ls103BL";

/// Build the `UtaMsCallPsAttachApnConfigReq` payload for `apn`.
pub fn attach_config(apn: &str) -> Result<Vec<u8>, CodecError> {
    let apn_bytes = apn.as_bytes();
    if apn_bytes.len() > APN_MAX_LEN {
        return Err(CodecError::StringOverflow {
            valid: apn_bytes.len(),
            capacity: APN_MAX_LEN,
        });
    }
    let mut apn_string = [0u8; APN_MAX_LEN];
    apn_string[..apn_bytes.len()].copy_from_slice(apn_bytes);

    let args: &[Arg<'_>] = &[
        Arg::Int(0),
        Arg::Bytes(&[0u8; 257]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 20]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 101]),
        Arg::Bytes(&[0u8; 257]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 20]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 101]),
        Arg::Bytes(&[0u8; 257]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(1028),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 20]),
        Arg::Int(3),
        Arg::Bytes(&apn_string),
        Arg::Bytes(&[0u8; 257]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 65]),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 250]),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Int(1028),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(1),
        Arg::Int(0),
        Arg::Int(0),
        Arg::Bytes(&[0u8; 20]),
        Arg::Int(3),
        Arg::Bytes(&apn_string),
        Arg::Int(3),
        Arg::Int(0),
    ];
    codec::pack(FORMAT, args)
}
