// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
//! Firmware RPC call identifiers.
//!
//! Ported from the reverse-engineered `xmm7360-pci` protocol tables.

/// A firmware RPC command identifier.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub struct CallId(pub u32);

impl CallId {
    /// Construct a call id from its raw wire value.
    pub const fn new(raw: u32) -> Self {
        Self(raw)
    }

    /// The raw wire value.
    pub const fn raw(self) -> u32 {
        self.0
    }
}

impl core::fmt::Display for CallId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match call_name(self.0) {
            Some(name) => f.write_str(name),
            None => write!(f, "0x{:x}", self.0),
        }
    }
}

/// Every known call identifier, sorted by wire value.
pub const CALL_IDS: &[(&str, u32)] = &[
    ("UtaMsSimOpenReq", 0x1),
    ("UtaMsSimApduCmdReq", 0x2),
    ("UtaMsSimApplicationReq", 0x4),
    ("UtaMsSimDecodeFcp", 0x6),
    ("UtaMsSimPbReadEntryReq", 0xd),
    ("UtaMsSimGenPinReq", 0xf),
    ("UtaMsSimModifyLockReq", 0x11),
    ("UtaMsSimTkProactiveCommandRsp", 0x16),
    ("UtaMsSimTkEnvelopeCommandReq", 0x17),
    ("UtaMsSimTkTerminalProfileReadReq", 0x19),
    ("UtaMsSimTkRegisterHandler", 0x1c),
    ("UtaMsSimTkDeregisterHandler", 0x1d),
    ("UtaMsCpsSetModeReq", 0x1f),
    ("UtaMsCpsSetStackModeConfiguration", 0x20),
    ("UtaMsCpsSetSimModeConfiguration", 0x21),
    ("UtaMsCpsReadImei", 0x23),
    ("UtaMsCallCsInit", 0x24),
    ("UtaMsCbsInit", 0x25),
    ("UtaMsSsInit", 0x26),
    ("UtaMsSsSendUssdReq", 0x27),
    ("UtaMsSsRespondUssd", 0x28),
    ("UtaMsSsAbort", 0x29),
    ("UtaMsSmsInit", 0x30),
    ("UtaMsSmsSendReq", 0x31),
    ("UtaMsSmsSetMemoryAvailableReq", 0x34),
    ("UtaMsSmsIncomingSmsAck", 0x36),
    ("UtaMsSmsSimMsgCountReq", 0x38),
    ("UtaMsCallPsInitialize", 0x3a),
    ("UtaMsCallPsObtainPdpContextId", 0x3b),
    ("UtaMsCallPsReleasePdpContextId", 0x3c),
    ("UtaMsCallPsDefinePrimaryReq", 0x3d),
    ("UtaMsCallPsUndefinePrimaryReq", 0x3f),
    ("UtaMsCallPsGetPrimaryReq", 0x41),
    ("UtaMsCallPsSetAuthenticationReq", 0x43),
    ("UtaMsCallPsSetDnsReq", 0x45),
    ("UtaMsCallPsGetNegotiatedDnsReq", 0x47),
    ("UtaMsCallPsGetNegIpAddrReq", 0x49),
    ("UtaMsCallPsActivateReq", 0x4b),
    ("UtaMsCallPsDeactivateReq", 0x4e),
    ("UtaMsCallPsConnectReq", 0x51),
    ("UtaMsNetOpen", 0x53),
    ("UtaMsNetSetRadioSignalReporting", 0x54),
    ("UtaMsNetSingleShotRadioSignalReportingReq", 0x55),
    ("UtaMsNetAttachReq", 0x5c),
    ("UtaMsNetPsAttachReq", 0x5d),
    ("UtaMsNetPsDetachReq", 0x5e),
    ("UtaMsNetScanReq", 0x5f),
    ("UtaMsNetScanAbort", 0x60),
    ("UtaMsNetPowerDownReq", 0x61),
    ("UtaMsNetExtScanReq", 0x62),
    ("UtaMsNetSetFdConfigReq", 0x6e),
    ("UtaMsNetGetFdConfigReq", 0x71),
    ("UtaMsNetConfigureNetworkModeReq", 0x73),
    ("UtaMsNetRatModeStatusReq", 0x76),
    ("UtaNvmRead", 0x79),
    ("UtaNvmWrite", 0x7a),
    ("UtaNvmWriteCommit", 0x7b),
    ("UtaSysGetInfo", 0x7c),
    ("UtaRPCPSConnectSetupReq", 0x7d),
    ("UtaRPCPsConnectToDatachannelReq", 0x7e),
    ("UtaRPCPSConnectReleaseReq", 0x7f),
    ("UtaMsNetDcSetVoiceDomainPreferenceConfigReq", 0x80),
    ("UtaMsCallCsSetupVoiceCallReq", 0x82),
    ("UtaMsCallCsReleaseCallReq", 0x88),
    ("UtaMsCallCsAcceptCallReq", 0x8d),
    ("UtaMsCallCsSwapCallsReq", 0x90),
    ("UtaMsCallCsHoldCallReq", 0x92),
    ("UtaMsCallCsRetrieveCallReq", 0x94),
    ("UtaMsCallCsSplitMptyReq", 0x96),
    ("UtaMsCallCsJoinCallsReq", 0x98),
    ("UtaMsCallCsTransferCallsReq", 0x9a),
    ("UtaMsCallCsStartDtmfReq", 0x9c),
    ("UtaMsCallCsStopDtmfReq", 0x9e),
    ("UtaMsCallCsSetUus1Info", 0xa6),
    ("UtaMsCallCsSetTtyDeviceMode", 0xa7),
    ("UtaMsCallCsGetTtyDeviceMode", 0xa8),
    ("UtaMsCallMultimediaSetupCallReq", 0xac),
    ("UtaMsCallMultimediaUpdateCallReq", 0xad),
    ("UtaMsCpsSetSimModeReq", 0xb0),
    ("UtaMsSsCallForwardReq", 0xb2),
    ("UtaMsSsCallWaitingReq", 0xb4),
    ("UtaMsSsCallBarringReq", 0xb6),
    ("UtaMsSsIdentificationReq", 0xb8),
    ("UtaMsSmsSetSendMoreMessagesStatus", 0xba),
    ("UtaMsSmsDataDownloadReq", 0xbb),
    ("UtaMsSmsDataDownloadAck", 0xbd),
    ("UtaMsCallPsGetNegQosReq", 0xbe),
    ("UtaMsCallPsGetTftReq", 0xc0),
    ("UtaMsCallPsSetPcoReq", 0xc2),
    ("UtaMsCallPsGetNwPcoReq", 0xc4),
    ("UtaMsCallPsNwActivateAcceptReq", 0xc7),
    ("UtaMsCallPsNwActivateRejectReq", 0xc9),
    ("UtaMsCallPsSetDataPrefReq", 0xcd),
    ("UtaMsCbsStartReq", 0xcf),
    ("UtaMsCbsStopReq", 0xd0),
    ("UtaMsCbsSetMsgFilter", 0xd3),
    ("UtaMsCbsGetMsgFilter", 0xd4),
    ("UtaMsCbsEtwsConfigReq", 0xd6),
    ("UtaMsCbsEtwsStartReq", 0xd8),
    ("UtaMsCbsEtwsStopReq", 0xda),
    ("UtaMsCpsNvmWrite", 0xde),
    ("UtaMsCpsNvmRead", 0xdf),
    ("UtaMsNetConfigureRxDiversityDarp", 0xe0),
    ("UtaMsNetLdrGetApnParameterList", 0xe2),
    ("UtaMsNetTimeInfoReadReq", 0xe3),
    ("UtaMsNetSetCsgConfigReq", 0xe6),
    ("UtaMsNetBandStatusReq", 0xe7),
    ("UtaMsNetGetExtendedRadioSignalInfoReq", 0xec),
    ("UtaMsNetDetachReq", 0xef),
    ("UtaMsNetSelectGprsClassReq", 0xf1),
    ("UtaMsNetGetCsgConfigReq", 0xf3),
    ("UtaMsNetCsServiceNotificationAccept", 0xf4),
    ("UtaMsNetSingleShotFdReq", 0xf9),
    ("UtaMsSimPbLocationReq", 0xfb),
    ("UtaMsSimPbReadGasEntryReq", 0xfd),
    ("UtaMsSimPbWriteEntryReq", 0xff),
    ("UtaMsSimPbGetMetaInformationReq", 0x101),
    ("UtaMsSimPbUsimPbSelectReq", 0x103),
    ("UtaMsSimPbGetFreeRecordsReq", 0x105),
    ("UtaMsSimCreateReadBinaryApdu", 0x10a),
    ("UtaMsSimCreateUpdateBinaryApdu", 0x10b),
    ("UtaMsSimAnalyseReadResult", 0x10c),
    ("UtaMsSimSetFdnReq", 0x10e),
    ("SetApScreenState", 0x110),
    ("UtaIoCtl", 0x111),
    ("UtaIdcApMsgSetReq", 0x114),
    ("UtaIdcApMsgGetReq", 0x115),
    ("UtaIdcEnbleReq", 0x116),
    ("UtaIdcCwsMsgSetReq", 0x119),
    ("UtaIdcCwsMsgGetReq", 0x11a),
    ("UtaIdcSubscribeIndications", 0x11c),
    ("UtaIdcUnsubscribeIndications", 0x11d),
    ("UtaBootPrepareShutdownReq", 0x11f),
    ("UtaBootShutdownReq", 0x120),
    ("UtaRfMaxTxPwrSet2g", 0x121),
    ("UtaRfMaxTxPwrSet3g", 0x122),
    ("UtaRfMaxTxPwrSet4g", 0x123),
    ("UtaFreqInfoActivateReq", 0x128),
    ("UtaFreqInfoGetFreqInfoReq", 0x129),
    ("UtaFreqInfoDeactivateReq", 0x12a),
    ("UtaFreqInfoRegisterIndications", 0x12b),
    ("UtaFreqInfoDeregisterIndications", 0x12c),
    ("UtaModeSetReq", 0x12f),
    ("UtaNvmFlushSync", 0x130),
    ("UtaProdRegisterGtiCallbackFunc", 0x132),
    ("UtaProdGtiCmdReq", 0x133),
    ("UtaCellTimeStampReq", 0x134),
    ("UtaMsSsLcsInit", 0x136),
    ("UtaMsSsLcsMoLocationReq", 0x137),
    ("UtaMsSsLcsMtlrNotificationRsp", 0x139),
    ("UtaMsCpAssistanceDataInjectReq", 0x13c),
    ("UtaMsCpResetAssistanceData", 0x13d),
    ("UtaMsCpPosMeasurementReq", 0x140),
    ("UtaMsCpPosMeasurementAbortReq", 0x142),
    ("UtaMsCpPosEnableMeasurementReport", 0x144),
    ("UtaMsCpPosDisableMeasurementReport", 0x145),
    ("UtaMsSimTkInit", 0x146),
    ("UtaMsSimTkExecSmsPpRsp", 0x148),
    ("UtaMsSimTkExecSimInitiatedCallRsp", 0x14a),
    ("UtaMsSimTkExecSsUssdRsp", 0x14c),
    ("UtaMsSimTkExecDtmfRsp", 0x14e),
    ("UtaMsSimTkStopDtmfReq", 0x150),
    ("UtaMsSimTkRefreshConfirmRsp", 0x152),
    ("UtaMsSimTkRefreshFcnRsp", 0x154),
    ("UtaMsSimTkControlReq", 0x155),
    ("UtaMsSimTkTerminalProfileDownloadReq", 0x157),
    ("UtaMs3gpp2SmsSendReq", 0x15a),
    ("UtaMs3gpp2SmsSubscribeIndications", 0x15c),
    ("UtaMs3gpp2SmsUnsubscribeIndications", 0x15d),
    ("RpcGetRemoteVerInfo", 0x15e),
    ("UtaMsMetricsRegisterHandler", 0x160),
    ("UtaMsMetricsDeregisterHandler", 0x161),
    ("UtaMsMetricsSetOptions", 0x162),
    ("UtaMsMetricsTrigger", 0x163),
    ("UtaMsEmbmsInit", 0x164),
    ("UtaMsEmbmsSetServiceReq", 0x165),
    ("UtaMsEmbmsMbsfnAreaConfigReq", 0x166),
    ("UtaMsEmbmsSessionConfigReq", 0x167),
    ("UtaMsEmbmsSetInterestedTMGIListReq", 0x168),
    ("UtaMsEmbmsSetInterestedSAIFreqReq", 0x169),
    ("UtaImsSubscribeIndications", 0x176),
    ("UtaImsUnsubscribeIndications", 0x177),
    ("UtaImsGetFrameworkState", 0x178),
    ("UtaRtcGetDatetime", 0x179),
    ("UtaMsSimAnalyseSimApduResult", 0x17a),
    ("UtaMsSimOpenChannelReq", 0x17b),
    ("UtaMsSimCloseChannelReq", 0x17d),
    ("UtaMsSimSetBdnReq", 0x17f),
    ("UtaMsSetSimStackMappingReq", 0x181),
    ("UtaMsGetSimStackMappingReq", 0x183),
    ("UtaMsNetSetRadioSignalReportingConfiguration", 0x188),
    ("UtaPCIeEnumerationextTout", 0x189),
    ("UtaMsSimTkSetTerminalCapabilityReq", 0x18a),
    ("UtaMsSimTkReadTerminalCapabilityReq", 0x18c),
    ("CsiFccLockQueryReq", 0x18e),
    ("CsiFccLockGenChallengeReq", 0x190),
    ("CsiFccLockVerChallengeReq", 0x192),
    ("UtaSensorOpenReq", 0x194),
    ("UtaSensorCloseExt", 0x197),
    ("UtaSensorStartExt", 0x198),
    ("UtaSensorSetAlarmParamExt", 0x199),
    ("UtaSensorSetSchedulerParamExt", 0x19a),
    ("CsiSioIpFilterCntrlSetReq", 0x19b),
    ("UtaMsAccCurrentFreqInfoReq", 0x19d),
    ("CsiTrcAtCmndReq", 0x1a0),
    ("UtaMsSimApduCmdExtReq", 0x1a2),
    ("UtaMsNetGetPlmnNameInfoReq", 0x1a4),
    ("UtaMsNetGetCountryListReq", 0x1a7),
    ("UtaMsNetExtConfigureNetworkModeReq", 0x1a9),
    ("UtaMsNetExtBandStatusReq", 0x1ac),
    ("UtaMsCallPsAttachApnConfigReq", 0x1af),
    ("CsiMsCallPsInitialize", 0x1b1),
    ("UtaAudioEnableSource", 0x1b2),
    ("UtaAudioDisableSource", 0x1b3),
    ("UtaAudioConfigureDestinationExt", 0x1b4),
    ("UtaAudioSetDestinationsForSource", 0x1b5),
    ("UtaAudioSetVolumeForSource", 0x1b6),
    ("UtaAudioSetMuteForSourceExt", 0x1b7),
    ("UtaAudioSetVolumeForDestination", 0x1b8),
    ("UtaAudioSetMuteForDestinationExt", 0x1b9),
    ("UtaAudioConfigureSourceExt", 0x1ba),
    ("UtaAudioSetDestinationsForSourceExt", 0x1bb),
    ("UtaRPCScreenControlReq", 0x1bc),
    ("UtaMsCallPsReadContextStatusReq", 0x1bd),
    ("CsiMsSimAccessGetSimStateInfoReq", 0x1bf),
    ("CsiMsNetGetRegistrationInfoReq", 0x1c1),
    ("CsiSioIpFilterNewCntrlSetReq", 0x1c3),
    ("CsiMsNetLdrGetApnPlmnParameterListReq", 0x1c5),
    ("RPCGetAPIParamChangedBitmap", 0x1c8),
];

/// Look up a call id by its firmware name.
pub fn call_id(name: &str) -> Option<CallId> {
    CALL_IDS
        .iter()
        .find_map(|(n, id)| (*n == name).then_some(CallId(*id)))
}

/// Look up the firmware name of a call id.
pub fn call_name(raw: u32) -> Option<&'static str> {
    CALL_IDS
        .iter()
        .find_map(|(n, id)| (*id == raw).then_some(*n))
}
